name:                superbuffer
version:             0.3.1.2
synopsis:            Efficiently build a bytestring from smaller chunks
description:         Efficiently (both fast and memory efficient) build a bytestring from smaller chunks
homepage:            https://github.com/agrafix/superbuffer#readme
license:             BSD3
author:              Alexander Thiemann
maintainer:          mail@athiemann.net
copyright:           2016 - 2022 Alexander Thiemann <mail@athiemann.net>
category:            Web
extra-source-files:
  - README.md
  - stack.yaml
  - package.yaml

dependencies:
  - base >= 4.8 && < 5
  - bytestring < 0.12

ghc-options: -Wall

library:
  source-dirs: src
  exposed-modules:
    - Data.ByteString.SuperBuffer
    - Data.ByteString.SuperBuffer.Pure
  c-sources: cbits/superbuffer.c

tests:
  spec:
    cpp-options: -DTest
    main: Test.hs
    source-dirs: test
    dependencies:
      - HTF < 0.16
      - QuickCheck < 2.15
      - async
      - superbuffer
    ghc-options: -funfolding-use-threshold=16 -O2 -optc-Ofast

benchmarks:
  sbuf-bench:
    main: Bench.hs
    source-dirs: bench
    dependencies:
      - criterion < 1.3
      - superbuffer
      - buffer-builder
      - async
    ghc-options: -funfolding-use-threshold=16 -O2 -optc-Ofast
